import "./globals.css";
import "@fontsource/geist";
import '@fontsource-variable/geist-mono';
import QueryProvider from "@/lib/QueryProvider";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata = {
  title: "Text-2-SQL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      signInUrl="/login"
      signUpUrl="/signup"
      appearance={{ cssLayerName: 'clerk', }
    }>
      <html lang="en">
        <body className={`antialiased`} >
          <QueryProvider>
            {children}  
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}